import type { ContractorProfile } from '@/types/contractor';

export const MOCK_CONTRACTORS: ContractorProfile[] = [
  {
    id: 'c-001',
    type: 'company',
    displayName: 'Remonty Kowalski',
    companyName: 'Remonty Kowalski Sp. z o.o.',
    email: 'biuro@remontkowalski.pl',
    phone: '+48 600 100 200',
    city: 'Warszawa',
    serviceArea: { city: 'Warszawa', radiusKm: 30, regions: ['mazowieckie'] },
    specialties: [
      { categoryId: 'paint', categoryName: 'Malowanie' },
      { categoryId: 'wall-repair', categoryName: 'Naprawa scian' },
      { categoryId: 'skim-coat', categoryName: 'Szpachlowanie' },
    ],
    specializedJobIds: ['paint-walls', 'paint-ceiling', 'repaint-walls', 'wall-repair', 'skim-coat', 'primer-walls'],
    shortDescription: 'Kompleksowe remonty mieszkan i domow - malowanie, szpachlowanie, tapetowanie.',
    longDescription: 'Firma Remonty Kowalski dziala na rynku od 2012 roku. Specjalizujemy sie w remontach wykonczeniowych: malowanie, gladzie gipsowe, tapetowanie, drobne naprawy. Dzialamy na terenie Warszawy i okolic. Zapewniamy terminowosc, porzadek i fachowe doradztwo.',
    yearsExperience: 12,
    verificationStatus: 'business-verified',
    listingTier: 'premium',
    isPromoted: false,
    materialsIncluded: true,
    jobScales: ['small', 'medium', 'large'],
    responseTimeHours: 4,
    availableSoon: true,
    rating: 4.7,
    reviewCount: 48,
    verifiedReviewCount: 32,
    suitableForHouseBuildStages: ['plaster', 'paint', 'finishing'],
    currentLeadCapacity: 'available',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2025-03-20T14:00:00Z',
  },
  {
    id: 'c-002',
    type: 'individual',
    displayName: 'Marek Nowak - Plytki & Lazienki',
    email: 'marek.nowak@email.pl',
    phone: '+48 601 200 300',
    city: 'Krakow',
    serviceArea: { city: 'Krakow', radiusKm: 20, regions: ['malopolskie'] },
    specialties: [
      { categoryId: 'wall-tiles', categoryName: 'Plytki scienne' },
      { categoryId: 'floor-tiles', categoryName: 'Plytki podlogowe' },
      { categoryId: 'waterproofing', categoryName: 'Hydroizolacja lazienki' },
      { categoryId: 'silicone', categoryName: 'Silikonowanie' },
    ],
    specializedJobIds: ['wall-tiles-bathroom', 'floor-tiles', 'bathroom-waterproofing', 'grout-only', 'silicone-sealing', 'silicone-refresh', 'kitchen-backsplash'],
    shortDescription: 'Specjalista od lazienek - plytki, hydroizolacja, fugowanie, silikony.',
    longDescription: 'Jestem glazurnikiem z 8-letnim doswiadczeniem. Wykonuje kompleksowe remonty lazienek: od hydroizolacji, przez klejenie plytek (rowniez wielkoformatowych), po fugowanie i silikonowanie. Pracuje solo, dbam o kazdy detal.',
    yearsExperience: 8,
    verificationStatus: 'basic-verified',
    listingTier: 'basic',
    isPromoted: false,
    materialsIncluded: false,
    jobScales: ['small', 'medium'],
    responseTimeHours: 8,
    availableSoon: true,
    rating: 4.9,
    reviewCount: 32,
    verifiedReviewCount: 20,
    suitableForHouseBuildStages: ['tiling', 'bathroom', 'waterproofing'],
    currentLeadCapacity: 'available',
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2025-02-15T10:00:00Z',
  },
  {
    id: 'c-003',
    type: 'company',
    displayName: 'FloorMaster Podlogi',
    companyName: 'FloorMaster Sp. z o.o.',
    email: 'kontakt@floormaster.pl',
    city: 'Wroclaw',
    serviceArea: { city: 'Wroclaw', radiusKm: 40, regions: ['dolnoslaskie'] },
    specialties: [
      { categoryId: 'laminate', categoryName: 'Panele laminowane' },
      { categoryId: 'vinyl', categoryName: 'Panele winylowe' },
      { categoryId: 'floor-prep', categoryName: 'Przygotowanie podlozy' },
      { categoryId: 'skirting', categoryName: 'Listwy przypodlogowe' },
    ],
    specializedJobIds: ['laminate-flooring', 'vinyl-flooring', 'vinyl-glued', 'underlay-install', 'self-leveling', 'parquet-sanding', 'skirting-boards'],
    shortDescription: 'Profesjonalny montaz paneli, winyli i podlog - szybko, czysto, z gwarancja.',
    longDescription: 'FloorMaster to ekipa specjalizujaca sie wylacznie w podlogach. Wykonujemy: wylewki samopoziomujace, ukladanie paneli laminowanych i winylowych (SPC/LVT), montaz listew. Gwarantujemy terminowosc i jakosc.',
    yearsExperience: 6,
    verificationStatus: 'business-verified',
    listingTier: 'promoted',
    isPromoted: true,
    materialsIncluded: true,
    jobScales: ['medium', 'large'],
    responseTimeHours: 2,
    availableSoon: false,
    rating: 4.5,
    reviewCount: 21,
    verifiedReviewCount: 14,
    suitableForHouseBuildStages: ['flooring', 'finishing'],
    currentLeadCapacity: 'busy',
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2025-03-01T10:00:00Z',
  },
  {
    id: 'c-004',
    type: 'individual',
    displayName: 'Tomasz - Malarz',
    email: 'tomasz.malarz@email.pl',
    city: 'Gdansk',
    serviceArea: { city: 'Gdansk', radiusKm: 15, regions: ['pomorskie'] },
    specialties: [
      { categoryId: 'paint', categoryName: 'Malowanie' },
      { categoryId: 'primer', categoryName: 'Gruntowanie' },
    ],
    specializedJobIds: ['paint-walls', 'paint-ceiling', 'repaint-walls', 'primer-walls', 'door-painting', 'paint-frames'],
    shortDescription: 'Malowanie scian i sufitow, gruntowanie. Szybko, czysto, uczciwie.',
    yearsExperience: 4,
    verificationStatus: 'unverified',
    listingTier: 'free',
    isPromoted: false,
    materialsIncluded: false,
    jobScales: ['small'],
    responseTimeHours: 24,
    availableSoon: true,
    rating: 4.2,
    reviewCount: 7,
    currentLeadCapacity: 'available',
    createdAt: '2025-01-20T10:00:00Z',
    updatedAt: '2025-03-10T10:00:00Z',
  },
  {
    id: 'c-005',
    type: 'company',
    displayName: 'BudMax Remonty',
    companyName: 'BudMax Remonty S.C.',
    email: 'info@budmax.pl',
    phone: '+48 602 300 400',
    city: 'Poznan',
    serviceArea: { city: 'Poznan', radiusKm: 50, regions: ['wielkopolskie'] },
    specialties: [
      { categoryId: 'paint', categoryName: 'Malowanie' },
      { categoryId: 'wall-tiles', categoryName: 'Plytki scienne' },
      { categoryId: 'floor-tiles', categoryName: 'Plytki podlogowe' },
      { categoryId: 'laminate', categoryName: 'Panele laminowane' },
      { categoryId: 'gypsum', categoryName: 'Sucha zabudowa (GK)' },
      { categoryId: 'waterproofing', categoryName: 'Hydroizolacja lazienki' },
    ],
    shortDescription: 'Kompleksowe remonty od A do Z - lazienki, kuchnie, pokoje. Duze i male zlecenia.',
    longDescription: 'BudMax Remonty to sprawdzona ekipa remontowa z Poznania. Wykonujemy pelen zakres prac wykonczeniowych: od gladzi i malowania, przez plytki i podlogi, po montaz zabudow GK. Dzialamy w Poznaniu i okolicach do 50 km.',
    yearsExperience: 15,
    verificationStatus: 'featured',
    listingTier: 'premium',
    isPromoted: true,
    materialsIncluded: true,
    jobScales: ['small', 'medium', 'large'],
    responseTimeHours: 6,
    availableSoon: true,
    rating: 4.6,
    reviewCount: 63,
    verifiedReviewCount: 45,
    suitableForHouseBuildStages: ['plaster', 'tiling', 'flooring', 'paint', 'finishing', 'bathroom', 'kitchen'],
    currentLeadCapacity: 'available',
    createdAt: '2023-09-01T10:00:00Z',
    updatedAt: '2025-03-18T10:00:00Z',
  },
  {
    id: 'c-006',
    type: 'individual',
    displayName: 'Piotr - Sucha Zabudowa',
    email: 'piotr.gk@email.pl',
    city: 'Lodz',
    serviceArea: { city: 'Lodz', radiusKm: 25, regions: ['lodzkie'] },
    specialties: [
      { categoryId: 'gypsum', categoryName: 'Sucha zabudowa (GK)' },
      { categoryId: 'skim-coat', categoryName: 'Szpachlowanie' },
    ],
    shortDescription: 'Scianki dzialowe, sufity podwieszane, zabudowy GK - precyzyjne wykonanie.',
    yearsExperience: 10,
    verificationStatus: 'phone-verified',
    listingTier: 'basic',
    isPromoted: false,
    materialsIncluded: false,
    jobScales: ['medium', 'large'],
    responseTimeHours: 12,
    availableSoon: false,
    rating: 4.8,
    reviewCount: 15,
    suitableForHouseBuildStages: ['drywall', 'plaster'],
    currentLeadCapacity: 'busy',
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 'c-007',
    type: 'company',
    displayName: 'OknaPlus Serwis',
    companyName: 'OknaPlus Serwis Sp. z o.o.',
    email: 'serwis@oknaplus.pl',
    phone: '+48 603 400 500',
    city: 'Warszawa',
    serviceArea: { city: 'Warszawa', radiusKm: 35, regions: ['mazowieckie'] },
    specialties: [
      { categoryId: 'windows', categoryName: 'Okna i parapety' },
      { categoryId: 'doors', categoryName: 'Drzwi wewnetrzne' },
    ],
    shortDescription: 'Montaz i serwis okien, parapetow, drzwi wewnetrznych. Regulacje i uszczelnianie.',
    yearsExperience: 9,
    verificationStatus: 'basic-verified',
    listingTier: 'basic',
    isPromoted: false,
    materialsIncluded: true,
    jobScales: ['small', 'medium'],
    responseTimeHours: 8,
    availableSoon: true,
    rating: 4.4,
    reviewCount: 19,
    verifiedReviewCount: 12,
    suitableForHouseBuildStages: ['windows', 'doors'],
    currentLeadCapacity: 'available',
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2025-02-28T10:00:00Z',
  },
  {
    id: 'c-008',
    type: 'individual',
    displayName: 'Jan - Kuchnie i Montaze',
    email: 'jan.kuchnie@email.pl',
    city: 'Katowice',
    serviceArea: { city: 'Katowice', radiusKm: 20, regions: ['slaskie'] },
    specialties: [
      { categoryId: 'kitchen-tiles', categoryName: 'Kuchnia - plytki i wykonczenie' },
      { categoryId: 'fixtures', categoryName: 'Drobne montaze' },
    ],
    shortDescription: 'Montaz mebli kuchennych, backsplash, blaty. Drobne prace wykonczeniowe.',
    yearsExperience: 5,
    verificationStatus: 'email-verified',
    listingTier: 'free',
    isPromoted: false,
    materialsIncluded: false,
    jobScales: ['small', 'medium'],
    responseTimeHours: 48,
    availableSoon: true,
    rating: 4.0,
    reviewCount: 4,
    suitableForHouseBuildStages: ['kitchen', 'finishing'],
    currentLeadCapacity: 'available',
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-03-15T10:00:00Z',
  },

  // ─── Faza 4 — Fachowcy dla nowych modułów (HVAC/BSO/kominek/schody/MVHR) ──
  {
    id: 'c-fgaz-001',
    type: 'company',
    displayName: 'KlimaTech F-GAZ Warszawa',
    companyName: 'KlimaTech Sp. z o.o.',
    email: 'biuro@klimatech.pl',
    phone: '+48 602 100 555',
    city: 'Warszawa',
    serviceArea: { city: 'Warszawa', radiusKm: 50, regions: ['mazowieckie'] },
    specialties: [
      { categoryId: 'hvac', categoryName: 'Klimatyzacja i wentylacja' },
    ],
    specializedJobIds: ['air-conditioning-split', 'mechanical-ventilation-mvhr'],
    shortDescription: 'Certyfikat F-GAZ UDT - montaż klimatyzacji split i wentylacji mechanicznej z rekuperacją.',
    longDescription: 'Posiadamy aktualny certyfikat F-GAZ wydany przez Urząd Dozoru Technicznego. Specjalizujemy się w klimatyzacji split (Samsung, Daikin, LG, Mitsubishi) oraz w wentylacji mechanicznej z odzyskiem ciepła (Brink, Vents, Komfo). Wystawiamy protokoły szczelności wymagane przez producentów do zachowania gwarancji.',
    yearsExperience: 9,
    verificationStatus: 'business-verified',
    listingTier: 'premium',
    isPromoted: true,
    materialsIncluded: false,
    jobScales: ['small', 'medium', 'large'],
    responseTimeHours: 6,
    availableSoon: true,
    rating: 4.8,
    reviewCount: 67,
    verifiedReviewCount: 41,
    currentLeadCapacity: 'available',
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2026-05-20T14:00:00Z',
  },
  {
    id: 'c-bso-001',
    type: 'company',
    displayName: 'TermoFasada BSO Krakow',
    companyName: 'TermoFasada Sp. z o.o.',
    email: 'biuro@termofasada.pl',
    phone: '+48 600 200 777',
    city: 'Krakow',
    serviceArea: { city: 'Krakow', radiusKm: 80, regions: ['malopolskie'] },
    specialties: [
      { categoryId: 'insulation', categoryName: 'Ocieplenie elewacji' },
    ],
    specializedJobIds: ['eps-insulation-bso'],
    shortDescription: 'Ocieplenia BSO/ETICS - certyfikaty Atlas, Ceresit, Caparol. 12 lat doswiadczenia.',
    longDescription: 'Wykonujemy ocieplenia domow jednorodzinnych i budynkow uzytecznosci publicznej w systemach BSO/ETICS Atlas Stopter, Ceresit Ceretherm, Caparol. Posiadamy certyfikaty producentow + 10-letnia gwarancja systemowa. Pomoc w dotacji Czyste Powietrze.',
    yearsExperience: 12,
    verificationStatus: 'business-verified',
    listingTier: 'premium',
    isPromoted: false,
    materialsIncluded: true,
    jobScales: ['medium', 'large'],
    responseTimeHours: 12,
    availableSoon: false,
    rating: 4.7,
    reviewCount: 38,
    verifiedReviewCount: 22,
    currentLeadCapacity: 'busy',
    createdAt: '2023-09-15T10:00:00Z',
    updatedAt: '2026-04-10T14:00:00Z',
  },
  {
    id: 'c-fireplace-001',
    type: 'individual',
    displayName: 'Pawel Kominek - kominiarz mistrz',
    email: 'pawel@kominekmistrz.pl',
    phone: '+48 601 333 999',
    city: 'Poznan',
    serviceArea: { city: 'Poznan', radiusKm: 60, regions: ['wielkopolskie'] },
    specialties: [
      { categoryId: 'fireplace', categoryName: 'Kominek' },
    ],
    specializedJobIds: ['fireplace-installation'],
    shortDescription: 'Mistrz kominiarski + instalator kominkow z certyfikatami Kratki, Romotop, Spartherm.',
    longDescription: 'Posiadam dyplom mistrza kominiarskiego oraz certyfikaty montazu producentow Kratki, Romotop, Spartherm. Kompleksowo: dobor wkladu, montaz, izolacja, obudowa, odbior kominiarski, wpis do CEEB. Po montazu rowniez przeglady okresowe co 12 mies.',
    yearsExperience: 15,
    verificationStatus: 'business-verified',
    listingTier: 'premium',
    isPromoted: true,
    materialsIncluded: false,
    jobScales: ['small', 'medium'],
    responseTimeHours: 24,
    availableSoon: true,
    rating: 4.9,
    reviewCount: 52,
    verifiedReviewCount: 35,
    currentLeadCapacity: 'available',
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2026-05-30T14:00:00Z',
  },
  {
    id: 'c-stairs-001',
    type: 'company',
    displayName: 'Stolarnia Dab - Schody i Balustrady',
    companyName: 'Stolarnia Dab Janusz Nowak',
    email: 'biuro@stolarniadab.pl',
    phone: '+48 603 444 111',
    city: 'Wroclaw',
    serviceArea: { city: 'Wroclaw', radiusKm: 100, regions: ['dolnoslaskie'] },
    specialties: [
      { categoryId: 'stairs', categoryName: 'Schody' },
    ],
    specializedJobIds: ['interior-wooden-stairs'],
    shortDescription: 'Schody drewniane z dabu/buku - projekt 3D, produkcja CNC, montaz pod klucz.',
    longDescription: 'Specjalizujemy sie wylacznie w schodach drewnianych wewnetrznych. Drewno z certyfikatami FSC, suszone do 8-12%. Projekt 3D wizualizujacy schody w Twoim domu, produkcja CNC w warsztacie, montaz przez 2-osobowa ekipe. Gwarancja konstrukcji 5 lat, lakierowania 2 lata. Spelniamy wymogi WT 2021 i PN-EN 1995-1-1.',
    yearsExperience: 18,
    verificationStatus: 'business-verified',
    listingTier: 'premium',
    isPromoted: false,
    materialsIncluded: true,
    jobScales: ['small', 'medium'],
    responseTimeHours: 24,
    availableSoon: false,
    rating: 4.8,
    reviewCount: 41,
    verifiedReviewCount: 28,
    currentLeadCapacity: 'busy',
    createdAt: '2023-06-15T10:00:00Z',
    updatedAt: '2026-04-25T14:00:00Z',
  },
  {
    id: 'c-acoustic-001',
    type: 'individual',
    displayName: 'AkustykPro - sufity podwieszane',
    email: 'kontakt@akustykpro.pl',
    phone: '+48 604 555 222',
    city: 'Gdansk',
    serviceArea: { city: 'Gdansk', radiusKm: 70, regions: ['pomorskie'] },
    specialties: [
      { categoryId: 'ceiling-acoustic', categoryName: 'Sufit podwieszany akustyczny' },
      { categoryId: 'gypsum', categoryName: 'Sucha zabudowa' },
    ],
    specializedJobIds: ['acoustic-suspended-ceiling', 'gypsum-ceiling', 'gypsum-wall'],
    shortDescription: 'Montaz sufitow podwieszanych Armstrong, Ecophon, AMF - biura, sklepy, gabinety.',
    longDescription: 'Wykonuje sufity podwieszane modulowe (Armstrong, Ecophon, AMF) oraz GK na ruszcie. Specjalizacja w przestrzeniach komercyjnych - biura, sklepy, gabinety medyczne. Dostarczam projekt akustyczny + pomiary NRC po montazu.',
    yearsExperience: 8,
    verificationStatus: 'basic-verified',
    listingTier: 'basic',
    isPromoted: false,
    materialsIncluded: true,
    jobScales: ['small', 'medium', 'large'],
    responseTimeHours: 12,
    availableSoon: true,
    rating: 4.6,
    reviewCount: 19,
    verifiedReviewCount: 11,
    currentLeadCapacity: 'available',
    createdAt: '2024-08-10T10:00:00Z',
    updatedAt: '2026-05-15T14:00:00Z',
  },
];
