import type { ContractorProfile } from '@/types/contractor';

export const MOCK_CONTRACTORS: ContractorProfile[] = [
  {
    id: 'c-001',
    type: 'company',
    displayName: 'Remonty Kowalski',
    companyName: 'Remonty Kowalski Sp. z o.o.',
    email: 'biuro@remontkowalski.pl',
    phone: '+48 600 100 200',
    city: 'Warszawa',
    serviceArea: { city: 'Warszawa', radiusKm: 30, regions: ['mazowieckie'] },
    specialties: [
      { categoryId: 'paint', categoryName: 'Malowanie' },
      { categoryId: 'wall-repair', categoryName: 'Naprawa ścian' },
      { categoryId: 'skim-coat', categoryName: 'Szpachlowanie' },
    ],
    shortDescription: 'Kompleksowe remonty mieszkań i domów — malowanie, szpachlowanie, tapetowanie.',
    longDescription: 'Firma Remonty Kowalski działa na rynku od 2012 roku. Specjalizujemy się w remontach wykończeniowych: malowanie, gładzie gipsowe, tapetowanie, drobne naprawy. Działamy na terenie Warszawy i okolic. Zapewniamy terminowość, porządek i fachowe doradztwo.',
    yearsExperience: 12,
    verificationStatus: 'verified',
    listingTier: 'premium',
    isPromoted: false,
    materialsIncluded: true,
    jobScales: ['small', 'medium', 'large'],
    responseTimeHours: 4,
    availableSoon: true,
    rating: 4.7,
    reviewCount: 48,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2025-03-20T14:00:00Z',
  },
  {
    id: 'c-002',
    type: 'individual',
    displayName: 'Marek Nowak — Płytki & Łazienki',
    email: 'marek.nowak@email.pl',
    phone: '+48 601 200 300',
    city: 'Kraków',
    serviceArea: { city: 'Kraków', radiusKm: 20, regions: ['małopolskie'] },
    specialties: [
      { categoryId: 'wall-tiles', categoryName: 'Płytki ścienne' },
      { categoryId: 'floor-tiles', categoryName: 'Płytki podłogowe' },
      { categoryId: 'waterproofing', categoryName: 'Hydroizolacja łazienki' },
      { categoryId: 'silicone', categoryName: 'Silikonowanie' },
    ],
    shortDescription: 'Specjalista od łazienek — płytki, hydroizolacja, fugowanie, silikony.',
    longDescription: 'Jestem glazurnikiem z 8-letnim doświadczeniem. Wykonuję kompleksowe remonty łazienek: od hydroizolacji, przez klejenie płytek (również wielkoformatowych), po fugowanie i silikonowanie. Pracuję solo, dbam o każdy detal.',
    yearsExperience: 8,
    verificationStatus: 'verified',
    listingTier: 'basic',
    isPromoted: false,
    materialsIncluded: false,
    jobScales: ['small', 'medium'],
    responseTimeHours: 8,
    availableSoon: true,
    rating: 4.9,
    reviewCount: 32,
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2025-02-15T10:00:00Z',
  },
  {
    id: 'c-003',
    type: 'company',
    displayName: 'FloorMaster Podłogi',
    companyName: 'FloorMaster Sp. z o.o.',
    email: 'kontakt@floormaster.pl',
    city: 'Wrocław',
    serviceArea: { city: 'Wrocław', radiusKm: 40, regions: ['dolnośląskie'] },
    specialties: [
      { categoryId: 'laminate', categoryName: 'Panele laminowane' },
      { categoryId: 'vinyl', categoryName: 'Panele winylowe' },
      { categoryId: 'floor-prep', categoryName: 'Przygotowanie podłoży' },
      { categoryId: 'skirting', categoryName: 'Listwy przypodłogowe' },
    ],
    shortDescription: 'Profesjonalny montaż paneli, winyli i podłóg — szybko, czysto, z gwarancją.',
    longDescription: 'FloorMaster to ekipa specjalizująca się wyłącznie w podłogach. Wykonujemy: wylewki samopoziomujące, układanie paneli laminowanych i winylowych (SPC/LVT), montaż listew. Gwarantujemy terminowość i jakość.',
    yearsExperience: 6,
    verificationStatus: 'verified',
    listingTier: 'promoted',
    isPromoted: true,
    materialsIncluded: true,
    jobScales: ['medium', 'large'],
    responseTimeHours: 2,
    availableSoon: false,
    rating: 4.5,
    reviewCount: 21,
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2025-03-01T10:00:00Z',
  },
  {
    id: 'c-004',
    type: 'individual',
    displayName: 'Tomasz — Malarz',
    email: 'tomasz.malarz@email.pl',
    city: 'Gdańsk',
    serviceArea: { city: 'Gdańsk', radiusKm: 15, regions: ['pomorskie'] },
    specialties: [
      { categoryId: 'paint', categoryName: 'Malowanie' },
      { categoryId: 'primer', categoryName: 'Gruntowanie' },
    ],
    shortDescription: 'Malowanie ścian i sufitów, gruntowanie. Szybko, czysto, uczciwie.',
    yearsExperience: 4,
    verificationStatus: 'unverified',
    listingTier: 'free',
    isPromoted: false,
    materialsIncluded: false,
    jobScales: ['small'],
    responseTimeHours: 24,
    availableSoon: true,
    rating: 4.2,
    reviewCount: 7,
    createdAt: '2025-01-20T10:00:00Z',
    updatedAt: '2025-03-10T10:00:00Z',
  },
  {
    id: 'c-005',
    type: 'company',
    displayName: 'BudMax Remonty',
    companyName: 'BudMax Remonty S.C.',
    email: 'info@budmax.pl',
    phone: '+48 602 300 400',
    city: 'Poznań',
    serviceArea: { city: 'Poznań', radiusKm: 50, regions: ['wielkopolskie'] },
    specialties: [
      { categoryId: 'paint', categoryName: 'Malowanie' },
      { categoryId: 'wall-tiles', categoryName: 'Płytki ścienne' },
      { categoryId: 'floor-tiles', categoryName: 'Płytki podłogowe' },
      { categoryId: 'laminate', categoryName: 'Panele laminowane' },
      { categoryId: 'gypsum', categoryName: 'Sucha zabudowa (GK)' },
      { categoryId: 'waterproofing', categoryName: 'Hydroizolacja łazienki' },
    ],
    shortDescription: 'Kompleksowe remonty od A do Z — łazienki, kuchnie, pokoje. Duże i małe zlecenia.',
    longDescription: 'BudMax Remonty to sprawdzona ekipa remontowa z Poznania. Wykonujemy pełen zakres prac wykończeniowych: od gładzi i malowania, przez płytki i podłogi, po montaż zabudów GK. Działamy w Poznaniu i okolicach do 50 km.',
    yearsExperience: 15,
    verificationStatus: 'verified',
    listingTier: 'premium',
    isPromoted: true,
    materialsIncluded: true,
    jobScales: ['small', 'medium', 'large'],
    responseTimeHours: 6,
    availableSoon: true,
    rating: 4.6,
    reviewCount: 63,
    createdAt: '2023-09-01T10:00:00Z',
    updatedAt: '2025-03-18T10:00:00Z',
  },
  {
    id: 'c-006',
    type: 'individual',
    displayName: 'Piotr — Sucha Zabudowa',
    email: 'piotr.gk@email.pl',
    city: 'Łódź',
    serviceArea: { city: 'Łódź', radiusKm: 25, regions: ['łódzkie'] },
    specialties: [
      { categoryId: 'gypsum', categoryName: 'Sucha zabudowa (GK)' },
      { categoryId: 'skim-coat', categoryName: 'Szpachlowanie' },
    ],
    shortDescription: 'Ścianki działowe, sufity podwieszane, zabudowy GK — precyzyjne wykonanie.',
    yearsExperience: 10,
    verificationStatus: 'pending',
    listingTier: 'basic',
    isPromoted: false,
    materialsIncluded: false,
    jobScales: ['medium', 'large'],
    responseTimeHours: 12,
    availableSoon: false,
    rating: 4.8,
    reviewCount: 15,
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 'c-007',
    type: 'company',
    displayName: 'OknaPlus Serwis',
    companyName: 'OknaPlus Serwis Sp. z o.o.',
    email: 'serwis@oknaplus.pl',
    phone: '+48 603 400 500',
    city: 'Warszawa',
    serviceArea: { city: 'Warszawa', radiusKm: 35, regions: ['mazowieckie'] },
    specialties: [
      { categoryId: 'windows', categoryName: 'Okna i parapety' },
      { categoryId: 'doors', categoryName: 'Drzwi wewnętrzne' },
    ],
    shortDescription: 'Montaż i serwis okien, parapetów, drzwi wewnętrznych. Regulacje i uszczelnianie.',
    yearsExperience: 9,
    verificationStatus: 'verified',
    listingTier: 'basic',
    isPromoted: false,
    materialsIncluded: true,
    jobScales: ['small', 'medium'],
    responseTimeHours: 8,
    availableSoon: true,
    rating: 4.4,
    reviewCount: 19,
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2025-02-28T10:00:00Z',
  },
  {
    id: 'c-008',
    type: 'individual',
    displayName: 'Jan — Kuchnie i Montaże',
    email: 'jan.kuchnie@email.pl',
    city: 'Katowice',
    serviceArea: { city: 'Katowice', radiusKm: 20, regions: ['śląskie'] },
    specialties: [
      { categoryId: 'kitchen-tiles', categoryName: 'Kuchnia — płytki i wykończenie' },
      { categoryId: 'fixtures', categoryName: 'Drobne montaże' },
    ],
    shortDescription: 'Montaż mebli kuchennych, backsplash, blaty. Drobne prace wykończeniowe.',
    yearsExperience: 5,
    verificationStatus: 'unverified',
    listingTier: 'free',
    isPromoted: false,
    materialsIncluded: false,
    jobScales: ['small', 'medium'],
    responseTimeHours: 48,
    availableSoon: true,
    rating: 4.0,
    reviewCount: 4,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-03-15T10:00:00Z',
  },
];
