import type { ContractorPlanDefinition, ContractorEntitlementSet } from '@/types/contractor-plans';

const FREE_ENTITLEMENTS: ContractorEntitlementSet = {
  canAppearInSearch: true,
  canReceiveRequests: true,
  maxActiveRequestsPlaceholder: 3,
  canBeFeatured: false,
  canBePromoted: false,
  canUseCityPromotion: false,
  canUseCategoryPromotion: false,
  canUseStagePromotion: false,
  maxProfileGalleryItemsPlaceholder: 3,
  maxServiceAreasPlaceholder: 1,
  maxSpecialtiesPlaceholder: 3,
  canAccessLeadDetailsPlaceholder: false,
  canSeeAdvancedStatsPlaceholder: false,
  canUsePrioritySupportPlaceholder: false,
  maxPromotionSlots: 0,
  maxCategorySponsorships: 0,
};

const STARTER_ENTITLEMENTS: ContractorEntitlementSet = {
  canAppearInSearch: true,
  canReceiveRequests: true,
  maxActiveRequestsPlaceholder: 10,
  canBeFeatured: false,
  canBePromoted: false,
  canUseCityPromotion: false,
  canUseCategoryPromotion: false,
  canUseStagePromotion: false,
  maxProfileGalleryItemsPlaceholder: 10,
  maxServiceAreasPlaceholder: 2,
  maxSpecialtiesPlaceholder: 6,
  canAccessLeadDetailsPlaceholder: true,
  canSeeAdvancedStatsPlaceholder: false,
  canUsePrioritySupportPlaceholder: false,
  maxPromotionSlots: 0,
  maxCategorySponsorships: 0,
};

const PRO_ENTITLEMENTS: ContractorEntitlementSet = {
  canAppearInSearch: true,
  canReceiveRequests: true,
  maxActiveRequestsPlaceholder: 50,
  canBeFeatured: false,
  canBePromoted: true,
  canUseCityPromotion: true,
  canUseCategoryPromotion: true,
  canUseStagePromotion: false,
  maxProfileGalleryItemsPlaceholder: 30,
  maxServiceAreasPlaceholder: 5,
  maxSpecialtiesPlaceholder: 12,
  canAccessLeadDetailsPlaceholder: true,
  canSeeAdvancedStatsPlaceholder: true,
  canUsePrioritySupportPlaceholder: false,
  maxPromotionSlots: 2,
  maxCategorySponsorships: 2,
};

const FEATURED_ENTITLEMENTS: ContractorEntitlementSet = {
  canAppearInSearch: true,
  canReceiveRequests: true,
  maxActiveRequestsPlaceholder: 100,
  canBeFeatured: true,
  canBePromoted: true,
  canUseCityPromotion: true,
  canUseCategoryPromotion: true,
  canUseStagePromotion: true,
  maxProfileGalleryItemsPlaceholder: 50,
  maxServiceAreasPlaceholder: 10,
  maxSpecialtiesPlaceholder: 20,
  canAccessLeadDetailsPlaceholder: true,
  canSeeAdvancedStatsPlaceholder: true,
  canUsePrioritySupportPlaceholder: true,
  maxPromotionSlots: 5,
  maxCategorySponsorships: 5,
};

const ENTERPRISE_ENTITLEMENTS: ContractorEntitlementSet = {
  canAppearInSearch: true,
  canReceiveRequests: true,
  maxActiveRequestsPlaceholder: 999,
  canBeFeatured: true,
  canBePromoted: true,
  canUseCityPromotion: true,
  canUseCategoryPromotion: true,
  canUseStagePromotion: true,
  maxProfileGalleryItemsPlaceholder: 100,
  maxServiceAreasPlaceholder: 50,
  maxSpecialtiesPlaceholder: 50,
  canAccessLeadDetailsPlaceholder: true,
  canSeeAdvancedStatsPlaceholder: true,
  canUsePrioritySupportPlaceholder: true,
  maxPromotionSlots: 20,
  maxCategorySponsorships: 10,
};

export const SEED_PLANS: ContractorPlanDefinition[] = [
  {
    id: 'free',
    name: 'Darmowy',
    shortDescription: 'Podstawowa widocznosc w wyszukiwarce. Idealny na start.',
    monthlyPricePlaceholder: 0,
    yearlyPricePlaceholder: 0,
    status: 'active',
    displayOrder: 1,
    notes: 'Domyslny plan dla nowych wykonawcow.',
    entitlements: FREE_ENTITLEMENTS,
    highlightFeatures: ['Widocznosc w wyszukiwarce', 'Odbior do 3 zapytan', '3 zdjecia w galerii'],
    badge: undefined,
    color: '#94A3B8',
  },
  {
    id: 'starter',
    name: 'Starter',
    shortDescription: 'Wiecej mozliwosci i lepszy dostep do leadow.',
    monthlyPricePlaceholder: 49,
    yearlyPricePlaceholder: 470,
    status: 'active',
    displayOrder: 2,
    notes: 'Plan dla wykonawcow chcacych rosnac.',
    entitlements: STARTER_ENTITLEMENTS,
    highlightFeatures: ['Do 10 aktywnych zapytan', '10 zdjec w galerii', '2 obszary uslug', 'Dostep do szczegolow leadow'],
    badge: 'Starter',
    color: '#2563EB',
  },
  {
    id: 'pro',
    name: 'Pro',
    shortDescription: 'Pelna promocja, wiecej specjalizacji i statystyki.',
    monthlyPricePlaceholder: 149,
    yearlyPricePlaceholder: 1430,
    status: 'active',
    displayOrder: 3,
    notes: 'Plan dla aktywnych wykonawcow szukajacych wzrostu.',
    entitlements: PRO_ENTITLEMENTS,
    highlightFeatures: ['Mozliwosc promocji profilu', 'Promocja w miescie i kategorii', 'Do 50 zapytan', '30 zdjec', 'Zaawansowane statystyki'],
    badge: 'Pro',
    color: '#7C3AED',
  },
  {
    id: 'featured',
    name: 'Wyrozniony',
    shortDescription: 'Maksymalna widocznosc i pelne uprawnienia.',
    monthlyPricePlaceholder: 299,
    yearlyPricePlaceholder: 2870,
    status: 'active',
    displayOrder: 4,
    notes: 'Plan premium z pelnym zestawem narzedzi.',
    entitlements: FEATURED_ENTITLEMENTS,
    highlightFeatures: ['Profil wyrozniany', 'Promocja etapu budowy', 'Do 100 zapytan', '50 zdjec', 'Priorytetowe wsparcie', '5 slotow promocyjnych'],
    badge: 'Featured',
    color: '#D97706',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    shortDescription: 'Indywidualny plan dla duzych firm i sieci.',
    monthlyPricePlaceholder: 0,
    yearlyPricePlaceholder: 0,
    status: 'active',
    displayOrder: 5,
    notes: 'Cena ustalana indywidualnie. Kontakt: pomoc@asystentremontu.pl',
    entitlements: ENTERPRISE_ENTITLEMENTS,
    highlightFeatures: ['Nielimitowane zapytania', 'Pelna promocja', '100 zdjec', 'Indywidualna obsluga', 'Dedykowany opiekun'],
    badge: 'Enterprise',
    color: '#0F172A',
  },
];
