import type { PriceCategory, PriceSourceType } from '@/types/house-build';

export interface PriceReferenceSeed {
  readonly itemKey: string;
  readonly category: PriceCategory;
  readonly stageKey: string | null;
  readonly label: string;
  readonly unit: string;
  readonly priceMin: number;
  readonly priceMax: number;
  readonly baselinePrice: number;
  readonly regionCode: string;
  readonly regionLabel: string;
  readonly sourceName: string;
  readonly sourceType: PriceSourceType;
  readonly sourceUrl: string;
  readonly notes: string;
  readonly confidenceNote: string;
}

const LAST_UPDATED = '2026-04-02';

const PL_BASELINE = { regionCode: 'PL', regionLabel: 'Polska - bazowe planistyczne' };
const LODZKIE = { regionCode: 'PL-LD', regionLabel: 'Lodzkie / Lodz' };

const MARKET_SOURCE = {
  sourceName: 'Analiza rynku budowlanego PL',
  sourceType: 'market-planning' as PriceSourceType,
  sourceUrl: '',
  confidenceNote: 'Szerokie zakresy planistyczne - rzeczywiste koszty moga sie roznic.',
};

const REGIONAL_SOURCE = {
  sourceName: 'Cenniki regionalne - lodzkie',
  sourceType: 'regional-estimate' as PriceSourceType,
  sourceUrl: '',
  confidenceNote: 'Stawki regionalne - wycena wykonawcy moze sie roznic.',
};

const OPERATOR_SOURCE = {
  sourceName: 'Cenniki operatorow / dostawcow',
  sourceType: 'operator-tariff-reference' as PriceSourceType,
  sourceUrl: '',
  confidenceNote: 'Referencyjne stawki operatorskie - warunki lokalne maja priorytet.',
};

export const HOUSE_BUILD_PRICE_SEEDS: readonly PriceReferenceSeed[] = [
  {
    itemKey: 'house_sso_per_m2',
    category: 'full-house',
    stageKey: null,
    label: 'Stan surowy otwarty',
    unit: 'm2',
    priceMin: 2800, priceMax: 3500, baselinePrice: 3150,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Orientacyjny koszt za m2 pow. uzytkowej w stanie surowym otwartym.',
  },
  {
    itemKey: 'house_ssz_per_m2',
    category: 'full-house',
    stageKey: null,
    label: 'Stan surowy zamkniety',
    unit: 'm2',
    priceMin: 3700, priceMax: 4500, baselinePrice: 4100,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Orientacyjny koszt za m2 pow. uzytkowej w stanie surowym zamknietym.',
  },
  {
    itemKey: 'house_developer_per_m2',
    category: 'full-house',
    stageKey: null,
    label: 'Stan deweloperski',
    unit: 'm2',
    priceMin: 5000, priceMax: 6500, baselinePrice: 5750,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Orientacyjny koszt za m2 pow. uzytkowej w stanie deweloperskim.',
  },
  {
    itemKey: 'house_turnkey_per_m2',
    category: 'full-house',
    stageKey: null,
    label: 'Pod klucz',
    unit: 'm2',
    priceMin: 6000, priceMax: 9000, baselinePrice: 7500,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Orientacyjny koszt za m2 pow. uzytkowej pod klucz.',
  },

  {
    itemKey: 'house_100m2_developer_reference',
    category: 'example-case',
    stageKey: null,
    label: 'Dom 100 m2 - stan deweloperski',
    unit: 'szt',
    priceMin: 441000, priceMax: 441000, baselinePrice: 441000,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Przykladowa kalkulacja referencyjna.',
  },
  {
    itemKey: 'house_120m2_total_reference_low_high',
    category: 'example-case',
    stageKey: null,
    label: 'Dom 120 m2 - calkowity zakres',
    unit: 'szt',
    priceMin: 391000, priceMax: 663000, baselinePrice: 527000,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Calkowity szacunek budowy bez dzialki i kosztow dodatkowych.',
  },
  {
    itemKey: 'house_120m2_developer_reference_low_high',
    category: 'example-case',
    stageKey: null,
    label: 'Dom 120 m2 - stan deweloperski',
    unit: 'szt',
    priceMin: 540000, priceMax: 720000, baselinePrice: 630000,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Deweloperski zakres planistyczny.',
  },
  {
    itemKey: 'house_140m2_developer_reference',
    category: 'example-case',
    stageKey: null,
    label: 'Dom 140 m2 - stan deweloperski',
    unit: 'szt',
    priceMin: 535000, priceMax: 535000, baselinePrice: 535000,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Przykladowa kalkulacja referencyjna.',
  },

  {
    itemKey: 'ready_house_project',
    category: 'pre-build',
    stageKey: 'design-and-permits',
    label: 'Gotowy projekt domu',
    unit: 'szt',
    priceMin: 3500, priceMax: 9000, baselinePrice: 5500,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Zakup gotowego projektu domu z katalogu.',
  },
  {
    itemKey: 'project_adaptation',
    category: 'pre-build',
    stageKey: 'design-and-permits',
    label: 'Adaptacja projektu',
    unit: 'szt',
    priceMin: 2500, priceMax: 5000, baselinePrice: 3500,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Adaptacja projektu gotowego do warunkow lokalnych.',
  },

  {
    itemKey: 'foundation_walls_without_insulation',
    category: 'foundation',
    stageKey: 'foundation',
    label: 'Sciany fundamentowe (bez izolacji)',
    unit: 'm2',
    priceMin: 161, priceMax: 161, baselinePrice: 161,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Lacznie material + robocizna - srednia referencyjna.',
  },
  {
    itemKey: 'foundation_wall_materials_component',
    category: 'foundation',
    stageKey: 'foundation',
    label: 'Sciany fundamentowe - materialy',
    unit: 'm2',
    priceMin: 90, priceMax: 90, baselinePrice: 90,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Skladnik materialowy scian fundamentowych.',
  },
  {
    itemKey: 'foundation_wall_labor_component',
    category: 'foundation',
    stageKey: 'foundation',
    label: 'Sciany fundamentowe - robocizna',
    unit: 'm2',
    priceMin: 71, priceMax: 71, baselinePrice: 71,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Skladnik robocizny scian fundamentowych.',
  },
  {
    itemKey: 'strip_foundations_total_reference',
    category: 'foundation',
    stageKey: 'foundation',
    label: 'Fundamenty lawowe - calkosc',
    unit: 'm2',
    priceMin: 300, priceMax: 440, baselinePrice: 370,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Zakres kosztow fundamentow lawowych. Dokladna wartosc zalezy od projektu i warunkow gruntowych.',
  },
  {
    itemKey: 'slab_foundation_total_reference',
    category: 'foundation',
    stageKey: 'foundation',
    label: 'Plyta fundamentowa - standard',
    unit: 'm2',
    priceMin: 500, priceMax: 700, baselinePrice: 600,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Zakres kosztow plyty fundamentowej standardowej.',
  },
  {
    itemKey: 'slab_foundation_higher_spec_reference',
    category: 'foundation',
    stageKey: 'foundation',
    label: 'Plyta fundamentowa - podwyzszona specyfikacja',
    unit: 'm2',
    priceMin: 700, priceMax: 1000, baselinePrice: 850,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Plyta fundamentowa o podwyzszonej specyfikacji (np. z ogrzewaniem podlogowym).',
  },

  {
    itemKey: 'aerated_concrete_24cm_labor_lodzkie',
    category: 'structural-walls',
    stageKey: 'structural-walls',
    label: 'Beton komorkowy 24cm - robocizna',
    unit: 'm2',
    priceMin: 92.00, priceMax: 98.10, baselinePrice: 95.00,
    ...LODZKIE, ...REGIONAL_SOURCE,
    notes: 'Stawki regionalne za murowanie betonu komorkowego 24cm.',
  },
  {
    itemKey: 'ceramic_block_25cm_labor_lodzkie',
    category: 'structural-walls',
    stageKey: 'structural-walls',
    label: 'Pustak ceramiczny 25cm - robocizna',
    unit: 'm2',
    priceMin: 162, priceMax: 177, baselinePrice: 169.50,
    ...LODZKIE, ...REGIONAL_SOURCE,
    notes: 'Stawki regionalne za murowanie pustaka ceramicznego 25cm.',
  },
  {
    itemKey: 'silicate_18cm_labor_lodzkie',
    category: 'structural-walls',
    stageKey: 'structural-walls',
    label: 'Silka 18cm - robocizna',
    unit: 'm2',
    priceMin: 66.10, priceMax: 72.70, baselinePrice: 69.40,
    ...LODZKIE, ...REGIONAL_SOURCE,
    notes: 'Stawki regionalne za murowanie silikatow 18cm.',
  },

  {
    itemKey: 'roof_truss_simple_total',
    category: 'roof',
    stageKey: 'roof',
    label: 'Wiazary dachowe - prosty system',
    unit: 'm2',
    priceMin: 158, priceMax: 158, baselinePrice: 158,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Konstrukcja dachowa - prosty system kratownicowy.',
  },
  {
    itemKey: 'roof_truss_heavier_system_total',
    category: 'roof',
    stageKey: 'roof',
    label: 'Wiazary dachowe - ciezszy system',
    unit: 'm2',
    priceMin: 263, priceMax: 263, baselinePrice: 263,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Konstrukcja dachowa - ciezszy system (np. ceramika, dachowki betonowe).',
  },
  {
    itemKey: 'roofing_membrane_material',
    category: 'roof',
    stageKey: 'roof',
    label: 'Membrana dachowa - material',
    unit: 'm2',
    priceMin: 5.50, priceMax: 5.50, baselinePrice: 5.50,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Koszt materialu membrany dachowej.',
  },
  {
    itemKey: 'roofing_membrane_labor',
    category: 'roof',
    stageKey: 'roof',
    label: 'Membrana dachowa - robocizna',
    unit: 'm2',
    priceMin: 18, priceMax: 18, baselinePrice: 18,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Koszt montazu membrany dachowej.',
  },
  {
    itemKey: 'boarding_and_felt_material',
    category: 'roof',
    stageKey: 'roof',
    label: 'Deskowanie + papa - material',
    unit: 'm2',
    priceMin: 61, priceMax: 61, baselinePrice: 61,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Koszt materialow deskowania i papy.',
  },
  {
    itemKey: 'boarding_and_felt_labor',
    category: 'roof',
    stageKey: 'roof',
    label: 'Deskowanie + papa - robocizna',
    unit: 'm2',
    priceMin: 41, priceMax: 41, baselinePrice: 41,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Koszt montazu deskowania i papy.',
  },

  {
    itemKey: 'facade_insulation_eps_labor_lodzkie',
    category: 'facade-insulation',
    stageKey: 'insulation-energy',
    label: 'Izolacja elewacji EPS - robocizna',
    unit: 'm2',
    priceMin: 131, priceMax: 144, baselinePrice: 137.5,
    ...LODZKIE, ...REGIONAL_SOURCE,
    notes: 'Stawki regionalne za ukladanie izolacji EPS na elewacji.',
  },
  {
    itemKey: 'facade_insulation_mineral_wool_labor_lodzkie',
    category: 'facade-insulation',
    stageKey: 'insulation-energy',
    label: 'Izolacja elewacji welna mineralna - robocizna',
    unit: 'm2',
    priceMin: 165, priceMax: 178, baselinePrice: 171.5,
    ...LODZKIE, ...REGIONAL_SOURCE,
    notes: 'Stawki regionalne za ukladanie izolacji welna mineralna na elewacji.',
  },
  {
    itemKey: 'wooden_ceiling_insulation_labor_lodzkie',
    category: 'facade-insulation',
    stageKey: 'insulation-energy',
    label: 'Izolacja stropu drewnianego - robocizna',
    unit: 'm2',
    priceMin: 50.60, priceMax: 57.20, baselinePrice: 53.90,
    ...LODZKIE, ...REGIONAL_SOURCE,
    notes: 'Stawki regionalne za izolacje stropu drewnianego.',
  },
  {
    itemKey: 'clinker_brick_installation_lodzkie',
    category: 'facade-insulation',
    stageKey: 'exterior-finishing',
    label: 'Cegla klinkierowa - montaz',
    unit: 'm2',
    priceMin: 173, priceMax: 190, baselinePrice: 181.5,
    ...LODZKIE, ...REGIONAL_SOURCE,
    notes: 'Stawki regionalne za montaz cegly klinkierowej.',
  },

  {
    itemKey: 'electrical_point_reference',
    category: 'installations',
    stageKey: 'installations',
    label: 'Punkt elektryczny - referencja',
    unit: 'punkt',
    priceMin: 185.17, priceMax: 228.86, baselinePrice: 201.06,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Sredni koszt punktu elektrycznego (gniazdka, wlaczniki).',
  },
  {
    itemKey: 'electrical_new_point_reference',
    category: 'installations',
    stageKey: 'installations',
    label: 'Nowy punkt elektryczny',
    unit: 'punkt',
    priceMin: 180, priceMax: 250, baselinePrice: 215,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Nowy punkt elektryczny - zakres kosztow.',
  },
  {
    itemKey: 'water_sewer_point_reference',
    category: 'installations',
    stageKey: 'installations',
    label: 'Punkt wodno-kanalizacyjny',
    unit: 'punkt',
    priceMin: 770, priceMax: 770, baselinePrice: 770,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Koszt punktu wodno-kanalizacyjnego.',
  },
  {
    itemKey: 'central_heating_point_reference',
    category: 'installations',
    stageKey: 'installations',
    label: 'Punkt CO (grzejnikowy)',
    unit: 'punkt',
    priceMin: 240, priceMax: 280, baselinePrice: 258,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Koszt punktu centralnego ogrzewania.',
  },
  {
    itemKey: 'hydronic_underfloor_heating_reference',
    category: 'installations',
    stageKey: 'installations',
    label: 'Ogrzewanie podlogowe wodne',
    unit: 'm2',
    priceMin: 170, priceMax: 220, baselinePrice: 195,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Ogrzewanie podlogowe wodne - standardowy zakres.',
  },
  {
    itemKey: 'hydronic_underfloor_heating_complex_reference',
    category: 'installations',
    stageKey: 'installations',
    label: 'Ogrzewanie podlogowe wodne - zlozony',
    unit: 'm2',
    priceMin: 180, priceMax: 260, baselinePrice: 220,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Ogrzewanie podlogowe wodne - bardziej zlozony uklad.',
  },

  {
    itemKey: 'gypsum_plaster_labor_reference',
    category: 'interior',
    stageKey: 'interior-finishing',
    label: 'Tynk gipsowy - robocizna',
    unit: 'm2',
    priceMin: 43, priceMax: 45, baselinePrice: 44,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Robocizna za m2 tynku gipsowego.',
  },
  {
    itemKey: 'gypsum_plaster_full_service_reference',
    category: 'interior',
    stageKey: 'interior-finishing',
    label: 'Tynk gipsowy - pelna usluga',
    unit: 'm2',
    priceMin: 67, priceMax: 70, baselinePrice: 68.5,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Tynk gipsowy z materialem i robocizna.',
  },

  {
    itemKey: 'electricity_connection_over_200m_cable_extra',
    category: 'utility-connections',
    stageKey: 'installations',
    label: 'Przylacze elektryczne >200m - kabel, dodatkowy metr',
    unit: 'mb',
    priceMin: 43.73, priceMax: 43.73, baselinePrice: 43.73,
    ...PL_BASELINE, ...OPERATOR_SOURCE,
    notes: 'Doplata za kazdy metr kablowy ponad 200m.',
  },
  {
    itemKey: 'electricity_connection_over_200m_overhead_extra',
    category: 'utility-connections',
    stageKey: 'installations',
    label: 'Przylacze elektryczne >200m - napowietrzne, dodatkowy metr',
    unit: 'mb',
    priceMin: 32.30, priceMax: 32.30, baselinePrice: 32.30,
    ...PL_BASELINE, ...OPERATOR_SOURCE,
    notes: 'Doplata za kazdy metr napowietrzny ponad 200m.',
  },
  {
    itemKey: 'gas_connection_up_to_15m_reference',
    category: 'utility-connections',
    stageKey: 'installations',
    label: 'Przylacze gazowe do 15m',
    unit: 'szt',
    priceMin: 3588.70, priceMax: 3588.70, baselinePrice: 3588.70,
    ...PL_BASELINE, ...OPERATOR_SOURCE,
    notes: 'Referencyjny koszt przylacza gazowego do 15m trasy.',
  },
  {
    itemKey: 'gas_connection_over_15m_extra_reference',
    category: 'utility-connections',
    stageKey: 'installations',
    label: 'Przylacze gazowe >15m - dodatkowy metr',
    unit: 'mb',
    priceMin: 128.25, priceMax: 128.25, baselinePrice: 128.25,
    ...PL_BASELINE, ...OPERATOR_SOURCE,
    notes: 'Doplata za kazdy metr ponad 15m trasy gazowej.',
  },
  {
    itemKey: 'water_connection_reference',
    category: 'utility-connections',
    stageKey: 'installations',
    label: 'Przylacze wodociagowe',
    unit: 'mb',
    priceMin: 120, priceMax: 250, baselinePrice: 185,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Koszt za mb przylacza wodociagowego. Warunki lokalne maja priorytet.',
  },
  {
    itemKey: 'sewer_connection_reference',
    category: 'utility-connections',
    stageKey: 'installations',
    label: 'Przylacze kanalizacyjne',
    unit: 'mb',
    priceMin: 120, priceMax: 220, baselinePrice: 170,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Koszt za mb przylacza kanalizacyjnego. Warunki lokalne maja priorytet.',
  },
  {
    itemKey: 'water_or_sewer_connection_design_reference',
    category: 'utility-connections',
    stageKey: 'installations',
    label: 'Projekt przylacza wod-kan',
    unit: 'szt',
    priceMin: 1100, priceMax: 2500, baselinePrice: 1800,
    ...PL_BASELINE, ...MARKET_SOURCE,
    notes: 'Koszt projektu przylacza wodociagowego lub kanalizacyjnego.',
  },
];

export const PRICE_CATEGORY_LABELS: Record<PriceCategory, string> = {
  'full-house': 'Dom - calkowite zakresy',
  'example-case': 'Przyklady referencyjne',
  'pre-build': 'Projektowanie',
  'foundation': 'Fundamenty',
  'structural-walls': 'Sciany konstrukcyjne',
  'roof': 'Dach',
  'facade-insulation': 'Elewacja i izolacja',
  'installations': 'Instalacje',
  'interior': 'Wykonczenie wnetrz',
  'utility-connections': 'Przylacza mediow',
};

export const PRICE_CATEGORY_ORDER: readonly PriceCategory[] = [
  'full-house',
  'example-case',
  'pre-build',
  'foundation',
  'structural-walls',
  'roof',
  'facade-insulation',
  'installations',
  'interior',
  'utility-connections',
];

export const PRICE_DISCLAIMER =
  'To sa referencyjne ceny planistyczne oparte na wybranych zrodlach publicznych i szacunkach regionalnych. Rzeczywiste koszty moga sie roznic w zaleznosci od projektu, regionu, wykonawcy, systemu, materialow, terminu i warunkow na budowie.';

export const LAST_PRICE_UPDATE = LAST_UPDATED;
